jets: add `dor`, `mor`, `gor`
urbit/ares pull request #106
Opened 2023-10-05 20:25 UTC by matthew-levan

2023-10-05 21:14 UTC, joemfb commented on rust/ares/src/jets/order.rs
> +                    }
This isn't right. You're replacing `a` and `b` with their respective heads, then again taking head or tail when branching on their equality, which means the recursive calls will operate on the head of the head or the tail of the head.

2023-10-06 12:17 UTC, matthew-levan commented on rust/ares/src/jets/order.rs
> +                    }
Thank you.

2023-10-08 03:52 UTC, ashelkovnykov requested changes

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Noun {
1. This isn't removing the logic from `jet_lth`, it's just cloning it into a second place
2. A util `lth` function should not take a `NockStack` since it never allocates
3. I've been inconsistent thus far about where shared functions go: in `jets::util` or in `jets::[module]::util`. We should probably pick which one is canonical and stick with it from now on.

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets.rs
> +pub mod order;
Nit: not 4 characters. Also, I would have expected these to go into `hash.rs`.

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets/order.rs
> +use crate::jets::util::slot;
Style error imported from the file you copied: import above file descriptor comment

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets/order.rs
> + */
Forgot to update the file description

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets/order.rs
> +use crate::jets::order::util::dor;
This is a weird import, since this function is defined within this very file. I'm not actually sure what the canonical Rust style is in this case. I think it might be just prefixing the three call sites with `util::`.

2023-10-08 03:52 UTC, ashelkovnykov commented on rust/ares/src/jets/order.rs
> +    pub fn dor(stack: &mut NockStack, a: Noun, b: Noun) -> Result {
`dor` doesn't need to be passed a `NockStack` because neither it nor any function it calls ever allocate

2023-10-09 13:44 UTC, matthew-levan commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Noun {
3. `jets::math::util::lth` requires a `NockStack` because it uses the `Atom::as_ubig` function. Is there another function I could use instead, which doesn't require a stack?

2023-10-09 13:48 UTC, matthew-levan commented on rust/ares/src/jets.rs
> +pub mod order;
How about `sort`?

2023-10-09 19:03 UTC, ashelkovnykov commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Noun {
Yeah, you're right - I just tried replacing those calls with `as_bitslice()` and comparing those, but the comparator for `BitSlice`s is broken.

2023-10-09 19:44 UTC, ashelkovnykov commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Result {
The `util` version of `lth` should probably return a `bool` and let the `jet_lth` wrapper handle returning a `jets::Result`

2023-10-09 19:49 UTC, ashelkovnykov commented on rust/ares/src/jets/sort.rs
> +    pub fn dor(stack: &mut NockStack, a: Noun, b: Noun) -> Result {
Same as above - the `util` version should probably return `bool`

2023-10-09 19:56 UTC, ashelkovnykov commented on rust/ares/src/jets/sort.rs
> +            }
This is unidiomatic in Rust. The preferred syntax is:
```
match (a.either(), b.either()) {
    (Left(atom_a) Left(atom_b)) => lth(stack, atom_a, atom_b),
    (Left(_), Right(_)) => true,
    (Right(_), Left(_)) => false,
    (Right(cell_a), Right(cell_b)) => {
        let a_head = slot(cell_a, 2)?;
        let b_head = slot(cell_b, 2)?;
        let a_tail = slot(cell_a, 3)?;
        let b_tail = slot(cell_b, 3)?;
        if unsafe { a_head.raw_equals(b_head) } {
            dor(stack, a_tail, b_tail)
        } else {
            dor(stack, a_head, b_head)
        }
    }
}
```

2023-10-11 18:25 UTC, matthew-levan commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Result {
That sounds good, except how should we decide on whether to return a `bool` or loobean? It doesn't seem like we've standardized on this yet, across the rest of the codebase.

2023-10-13 15:01 UTC, ashelkovnykov approved these changes

2023-10-13 15:02 UTC, ashelkovnykov commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Result {
Yeah, there's no standard for utility functions so far, other than "what's easiest to work with for most of the functions calling the `util` function? So by that metric, I think returning a `loobean` `Atom` for `lth` and `dor` is fine.

2023-10-13 16:19 UTC, joemfb commented on rust/ares/src/jets/math.rs
> +    pub fn lth(stack: &mut NockStack, a: Atom, b: Atom) -> Result {
I think it's important to set a standard and stick to it. Booleans are obviously manageable -- loobeans actually are too. Switching between them unpredictably in C is not at all. But with rust's stronger type system it might be ...

/cc @eamsden

2023-10-20 18:14 UTC, merged