Jets for `min`, `max`, and `peg`
urbit/ares pull request #117
Opened 2023-10-25 02:15 UTC by ashelkovnykov

2023-10-26 05:57 UTC, ashelkovnykov commented on rust/ares/Cargo.toml
> +sham_hints = []
Merge error

2023-10-26 05:57 UTC, ashelkovnykov commented on rust/ares/src/jets/bits.rs
> +        // let (a0, a24, _a63, a96, a128) = atoms(&mut c.stack);
Forgot to uncomment tests

2023-11-07 12:53 UTC, eamsden requested changes

2023-11-07 12:53 UTC, eamsden commented on rust/ares/src/jets/tree.rs
> +pub fn jet_peg(context: &mut Context, subject: Noun) -> Result {
in general this would do less copying, and arguably be clearer, if it were written in terms of bitslices. The idea is to allocate an indirect atom that can hold `(sub 1 (add (met 0 a) (met 0 b)))` bits, copy all but the MSB of `b` in, then copy all of `a` in. We omit the MSB of `b` since the MSB of an axis is the size marker, and all bits following are the actual path.

2023-11-10 16:40 UTC, eamsden commented
I rewrote `jet_peg` and `jet_mas` to use bitslices: 4177ae6

2023-11-10 16:41 UTC, eamsden commented on rust/ares/src/jets/tree.rs
> +pub fn jet_peg(context: &mut Context, subject: Noun) -> Result {
See 4177ae6 / `eamsden/peg-mas-bitslice` branch

2023-11-15 10:33 UTC, ashelkovnykov commented on rust/ares/src/jets/tree.rs
> +pub fn jet_peg(context: &mut Context, subject: Noun) -> Result {
You're right. The previous version was written using the existing jets as reference material, which at the time did not have @joemfb 's rewrite of the `+cap`, `+mas`, and `+peg` jets in [397](https://github.com/urbit/vere/pull/397) merged. I was also ignorant at the time of the relationship between the aforementioned jets and the bits of the input / output (which was rectified by reviewing the above-linked PR).

For posterity:
- `+cap` just checks whether the second-to-most significant bit of the input is `1` or `0`
- `+mas` just replaces the two most significant bits of the input with `01`
- `+peg` (as @eamsden explains above) just concatenates the bits of the input, excluding the most significant bit of either, and then sets the next most significant bit after the concatenation to `1`

2023-11-15 10:39 UTC, ashelkovnykov commented
@eamsden I applied your changes.

There was a "wrong bitshift direction" bug that didn't get caught by the tests, because it would allocate too many words, so there was no actual problem (just memory inefficiency). I added tests for the case, but it looks like the bug is not detectable after the fact because the excessive size is resolved by normalization to atom.

I'll leave the tests in, but I'm not sure how we would catch bugs like this with tests.

2023-11-15 12:37 UTC, eamsden commented
> @eamsden I applied your changes.
> 
> There was a "wrong bitshift direction" bug that didn't get caught by the tests, because it would allocate too many words, so there was no actual problem (just memory inefficiency). I added tests for the case, but it looks like the bug is not detectable after the fact because the excessive size is resolved by normalization to atom.
> 
> I'll leave the tests in, but I'm not sure how we would catch bugs like this with tests.

Good catch!

The test would have to be somewhat imprecise and check that the allocation didn't exceed what was reasonable. That wrong bitshift would have increased the allocation size from what was necessary by a factor of 4k, so it shouldn't be too hard to catch with thresholding. I'll make an issue to have tests like this.

2023-11-15 12:38 UTC, eamsden approved these changes

2023-11-15 12:38 UTC, eamsden commented on rust/ares/src/jets/tree.rs
> +    let out_words = (out_bits + 63) >> 6; // bits to 8-byte words
good catch!

2023-11-15 12:38 UTC, merged