Add jet for `+zing`
urbit/ares pull request #119
Opened 2023-10-27 12:05 UTC by ashelkovnykov

Add jet for `+zing` and use it to correctly weld the `$tang` of trace messages prior to passing the trace as input to `+mook`.

2023-11-07 15:21 UTC, eamsden requested changes

2023-11-07 15:21 UTC, eamsden commented on rust/ares/src/jets/text.rs
> +    pub fn zing(stack: &mut NockStack, mut list: Noun) -> jets::Result {
This would be *much* clearer if written in destination-passing / "tail modulo cons" style.

- Set `res = D(0)`
- Keep a mutable noun pointer, initially `&mut res`.
- Whenever a new list element is discovered, allocate a new cell for it. Write the cell through the destination pointer, write the element to the head of the cell, set the pointer to the tail as the new destination pointer.
- When the outer loop exits, write `D(0)` to the destination pointer, then return `res`.

2023-11-10 16:47 UTC, eamsden commented on rust/ares/src/jets/text.rs
> +    pub fn zing(stack: &mut NockStack, mut list: Noun) -> jets::Result {
I made this change in 4500427e4ae28031cac79b4fd13ba3e17311ff3b / `eamsden/zing`

2023-11-15 10:54 UTC, ashelkovnykov commented on rust/ares/src/jets/text.rs
> +    pub fn zing(stack: &mut NockStack, mut list: Noun) -> jets::Result {
Yes, this is clearly superiour

2023-11-15 12:52 UTC, eamsden approved these changes

2023-11-15 12:52 UTC, merged