integrate urcrypt jets
urbit/ares pull request #123
Opened 2023-11-10 04:51 UTC by eamsden

Merges and updates #90 cc @matthew-levan 

should be merged after the `as/demo-debug` branch and #122 cc @ashelkovnykov 

depends on urbit/urcrypt#1

- [x] fix shell.nix to build urcrypt and make it available to the rust build
- [x] update urcrypt jet prototypes and error returns
- [ ] fix cargo.toml to import new version of urcrypt-sys (requires @matthew-levan to merge urbit/urcrypt#1 and push a new version of the crate to crates.io)
- [x] add SHA jets to hot state
- [x] add ED jets to hot state
- [ ] add AES jets to hot state
- [ ] debug %jael crash

2023-11-10 14:46 UTC, matthew-levan commented on rust/ares/Cargo.toml
> +#urcrypt-sys = "0.1.0"
You can use `urcrypt-sys = "0.1.1"` now.

2023-11-20 05:37 UTC, ashelkovnykov commented
Are there instructions for what needs to be done to build with `urcrypt`? Trying to run `cargo build` on this branch results in the following error for me:
```
  --- stderr
  thread 'main' panicked at /home/ashelkov/Tools/rust/rust-1.73.0/registry/src/index.crates.io-6f17d22bba15001f/urcrypt-sys-0.1.1/build.rs:6:92:
  called `Result::unwrap()` on an `Err` value: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--libs" "--cflags" "liburcrypt-0" "liburcrypt-0 >= 0.1.0"` did not exit successfully: exit status: 1
  error: could not find system library 'liburcrypt-0' required by the 'urcrypt-sys' crate
```

2023-11-20 13:55 UTC, eamsden commented
@ashelkovnykov this branch updates the `shell.nix` file, so you will need to exit and re-enter `nix-shell`

2023-11-20 20:13 UTC, matthew-levan commented
I pushed a few commits here. Other adding the AES jets to the hot state (which requires implementing the ability for Ares to match nested jets), this PR seems ready.

2023-11-22 08:31 UTC, ashelkovnykov requested changes
Most of the comments are regarding punting and stripping trailing `0`s from input. Two questions:
1. Why *does* Vere punt on invalid key length? Does it not result in  an error? If it does, shouldn't we just bail in the jet?
2. When do we need to strip trailing `0`s and when do we not need to do so?

2023-11-22 17:39 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +    if sec_key.bit_size() > 32 {
Almost certainly. Although, I don't actually see a size check on the secret or public key in the Hoon.

2023-11-22 18:01 UTC, matthew-levan commented on rust/ares/src/jets/lock/sha.rs
> +    let message = dat.as_bytes();
I don't know, I just replicated Vere's behavior and tests. When the tests pass, I call it good.

2023-11-22 18:06 UTC, matthew-levan commented on rust/ares/src/jets/lock/sha.rs
> +mod tests {
Some from existing tests in `urbit/urbit` and some from calling the respective functions in `dojo`.

2023-11-22 18:08 UTC, matthew-levan commented on rust/ares/src/jets/hot.rs
> +            Left(b"hex"),
I don't know, that looks like your commit there @ashelkovnykov. I didn't edit this file.

2023-11-22 18:10 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +mod tests {
`tests/sys/zuse/crypto/ed25519.hoon`

2023-11-22 18:12 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +    let sed = slot(sam, 3)?.as_atom()?;
Noted but does it really matter? We're supposed to get this thing working by February. My marching orders here were to write these crypto jets as fast as possible.

2023-11-22 18:14 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +    let key = slot(subject, 60)?.as_atom()?;
It's 64 in Vere.

2023-11-22 18:15 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +mod tests {
`tests/sys/zuse/crypto/aes.hoon`

2023-11-22 18:16 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +        };
Yes

2023-11-22 18:16 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +        };
Yes

2023-11-22 18:17 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +    if sec_key.bit_size() > 32 {
Also, this should probably punt instead of erroring deterministically. I don't see a size assertion in the hoon.

2023-11-22 18:17 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +    if pub_key.bit_size() > 32 {
Same answers

2023-11-22 18:17 UTC, eamsden commented on rust/ares/src/jets/lock/ed.rs
> +mod tests {
@matthew-levan please respond

2023-11-22 18:18 UTC, eamsden commented on rust/ares/src/jets/lock/sha.rs
> +    let message = dat.as_bytes();
@matthew-levan

2023-11-22 18:30 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +mod tests {
tfw responded before the boss could ask me too.

2023-11-22 18:52 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +        };
Hmm, is there a test you can think of that would prove this?

2023-11-23 03:22 UTC, ashelkovnykov commented on rust/ares/src/jets/hot.rs
> +            Left(b"hex"),
This is more of a question about the overall design of jets. @joemfb @frodwith ?

2023-11-23 05:06 UTC, joemfb commented on rust/ares/src/jets/hot.rs
> +            Left(b"hex"),
Old code, i don't think there are any remaining obstacles to rationalizing the hierarchy (there used to be solid-pill problems).

2023-11-23 15:27 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/ed.rs
> +    if sec_key.bit_size() > 32 {
> should probably punt
No, `sec`'s size is asserted via indirect call to `+puck` through `+suck`

2023-11-24 23:11 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +    if sec_key.bit_size() > 32 {
Doesn't calling `.as_direct()` ensure that `sec_key` is much less than 32 bytes already (less than 64 bits even), thus rendering the `bit_size()` checks useless? So.. we could just delete the lines?

2023-11-24 23:27 UTC, matthew-levan commented on rust/ares/src/jets/lock/sha.rs
> +    let message = dat.as_bytes();
I just tested behavior with and without dropping the trailing zeroes and found that it doesn't matter, at least for our tests. I changed the code to drop them anyways, since I think that's what Vere does.

2023-11-25 02:32 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/aes.rs
> +    let key = slot(subject, 60)?.as_atom()?;
No, it's 32:
```
static u3_noun
_cqea_siva_de(u3_atom key,
              u3_noun ads,
              u3_atom iv,
              u3_atom len,
              u3_atom txt)
{
  if ( u3r_met(3, key) > 32 ) {
    return u3_none;
  }
  ...
}
```
```
int
urcrypt_aes_siva_de(uint8_t *message,
                    size_t message_length,
                    urcrypt_aes_siv_data *data,
                    size_t data_length,
                    uint8_t key[32],
                    uint8_t iv[16],
                    uint8_t *out)
{
  return urcrypt__aes_siv_de(key, 32,
      message, message_length, data, data_length, iv, out);
}
```

2023-11-25 14:54 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/aes.rs
> +        };
Nevermind, I misread one part of the code. I verified it's the same functionality as in Vere.

2023-11-25 14:59 UTC, ashelkovnykov approved these changes

2023-11-27 23:11 UTC, merged