fix jet_puck
urbit/ares pull request #124
Opened 2023-11-14 05:04 UTC by eamsden

2023-11-20 20:14 UTC, matthew-levan approved these changes

2023-11-22 14:25 UTC, ashelkovnykov requested changes

2023-11-22 18:28 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
>      fn test_puck() {
`tests/sys/zuse/ed25519.hoon`

2023-11-22 18:35 UTC, eamsden commented on rust/ares/src/interpreter.rs
> +
yes it should

2023-11-22 18:36 UTC, eamsden commented on rust/ares/src/jets/warm.rs
> +                return Some((jet, path));
it is leftover from debugging, but should stay. It's helpful when debugging jet misses.

2023-11-24 13:58 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/ed.rs
>      fn test_puck() {
That's not actually the case: neither the old test value nor the new test value are from that test file (which uses the test vectors from [RFC 8032](https://tools.ietf.org/html/rfc8032#section-7.1)).

I double-checked the test values using `puck:ed:crypto` in a fake `zod` with Serf and left a "TODO" for expanding the test suite using the aforementioned vectors.

2023-11-24 14:02 UTC, ashelkovnykov approved these changes

2023-11-25 14:54 UTC, merged