Add u64/u128 atom exports
urbit/ares pull request #127
Opened 2023-11-15 21:33 UTC by sigilante

Necessary for floating-point; nice for conversions from direct atoms.

In particular, I'd like this expedited to complete `last` in the parsing jets.

2023-11-15 21:47 UTC, sigilante commented
Couldn't find the original `as_u64` to cherry-pick in, lost in the mists of past branches...

2023-11-15 21:57 UTC, joemfb commented on rust/ares/src/noun.rs
> +            u128_array[1] = self.as_direct()?.data();
I think these should be the other way around.

2023-11-15 22:03 UTC, eamsden requested changes

2023-11-15 22:03 UTC, eamsden commented on rust/ares/src/noun.rs
> +    }
Rust has a native u128 type: https://doc.rust-lang.org/std/primitive.u128.html

You could make a 16-element byte array, copy into it from `atom.as_bytes()`, and then call u128::from_le_bytes() on the array to get the atom.
```suggestion
    pub unsafe fn as_u128(self) -> Result<u128> {
        if self.size() <= 2 {
            let mut u128_array = [0u8; 16];
            let self_bytes = self.as_bytes();
            u128_array[0..self.as_bytes()].copy_from_slice(self_bytes);
            Ok(u128::from_le_bytes(u128_array)
        } else {
            Err(Error::NotRepresentable)
        }
    }
```

2023-11-15 22:03 UTC, eamsden commented on rust/ares/src/noun.rs
> +            Ok(*u128_array)
```suggestion
    pub unsafe fn as_u128(self) -> Result<[u64; 2]> {
        if self.is_direct() {
            Ok(self.data() as u128)
```

2023-11-15 22:03 UTC, eamsden commented on rust/ares/src/noun.rs
> +            unsafe { self.indirect.as_u128_pair() }
```suggestion
            unsafe { self.indirect.as_u128() }
```

2023-11-15 22:04 UTC, sigilante commented on rust/ares/src/noun.rs
> +    }
It's a pair of u64 to match the SoftFloat interface.

2023-11-15 22:04 UTC, sigilante commented on rust/ares/src/noun.rs
> +    }
It's not a generic u128, it's to solve a particular use case from urcrypt.

2023-11-15 22:05 UTC, sigilante commented on rust/ares/src/noun.rs
> +            u128_array[1] = self.as_direct()?.data();
It follows the SoftFloat order.

2023-11-15 22:06 UTC, sigilante commented on rust/ares/src/noun.rs
> +    }
~~urcrypt~~ urfloat, whatever we end up calling it

2023-11-15 22:14 UTC, eamsden requested changes

2023-11-15 22:14 UTC, eamsden commented on rust/ares/src/noun.rs
> +            u128_array[1] = self.as_direct()?.data();
Does the indirect case follow the softfloat order?

2023-11-15 22:14 UTC, eamsden commented on rust/ares/src/noun.rs
> +    pub unsafe fn as_u64_pair(self) -> Result<[u64; 2]> {
Doc comment please

2023-11-15 22:14 UTC, eamsden commented on rust/ares/src/noun.rs
> +    /* SoftFloat-compatible ordered pair of 64-bit words */
doc comment please

2023-11-15 22:33 UTC, sigilante commented on rust/ares/src/noun.rs
> +            u128_array[1] = self.as_direct()?.data();
While I'm always wary of endian/MSB-v-LSB issues like this, the test cases in https://github.com/urbit/ares/blob/sigilante/jetting-float-r-cores/rust/ares/src/jets/float_rq.rs did succeed; see e.g. `jet_rq_add()` therein.

2023-11-15 23:00 UTC, eamsden approved these changes

2023-11-15 23:18 UTC, joemfb commented
i think it's worth double checking here. I don't know anything about the softfloat crate in use, but vere's equivalent jets are clearly little-endian: https://github.com/urbit/vere/blob/629ac3698383be5c93324b5ed6355f4aac87dad9/pkg/noun/jets/e/rq.c#L57-L75

2023-11-15 23:23 UTC, sigilante commented
> i think it's worth double checking here. I don't know anything about the softfloat crate in use, but vere's equivalent jets are clearly little-endian: https://github.com/urbit/vere/blob/629ac3698383be5c93324b5ed6355f4aac87dad9/pkg/noun/jets/e/rq.c#L57-L75

I'll check before we merge and comment here when that's done.

2023-11-17 16:39 UTC, sigilante commented
This test passes as written:

```
    #[test]
    fn test_u64() {
        let c = &mut init_context();

        assert_eq!(D(0x0).as_atom().unwrap().as_u64(), Ok(0x0_u64));
        assert_eq!(D(0x1).as_atom().unwrap().as_u64(), Ok(0x1_u64));
        assert_eq!(D(0x3fffffffffffffff).as_atom().unwrap().as_u64(), Ok(0x3fffffffffffffff_u64));

        assert_eq!(A(&mut c.stack, &ubig!(0xffffffffffffffffffffffffffffffff)).as_atom().unwrap().as_u64_pair().unwrap(), [0xffffffffffffffff_u64, 0xffffffffffffffff_u64]);
        assert_eq!(A(&mut c.stack, &ubig!(0xfffffffffffffffffffffffffffffffe)).as_atom().unwrap().as_u64_pair().unwrap(), [0xfffffffffffffffe_u64, 0xffffffffffffffff_u64]);
        assert_eq!(A(&mut c.stack, &ubig!(0x7fff8000000000000000000000000000)).as_atom().unwrap().as_u64_pair().unwrap(), [0x0_u64, 0x7fff800000000000_u64]);
    }
```

2023-11-17 16:46 UTC, sigilante commented
```
#[test]
fn test_u64() {
    let c = &mut init_context();

    assert_eq!(D(0x0).as_atom().unwrap().as_u64(), Ok(0x0_u64));
    assert_eq!(D(0x1).as_atom().unwrap().as_u64(), Ok(0x1_u64));
    assert_eq!(D(0x3fffffffffffffff).as_atom().unwrap().as_u64(), Ok(0x3fffffffffffffff_u64));

    assert_eq!(A(&mut c.stack, &ubig!(0xffffffffffffffffffffffffffffffff)).as_atom().unwrap().as_u64_pair().unwrap(), [0xffffffffffffffff_u64, 0xffffffffffffffff_u64]);
    assert_eq!(A(&mut c.stack, &ubig!(0xfffffffffffffffffffffffffffffffe)).as_atom().unwrap().as_u64_pair().unwrap(), [0xfffffffffffffffe_u64, 0xffffffffffffffff_u64]);
    assert_eq!(A(&mut c.stack, &ubig!(0x7fff8000000000000000000000000000)).as_atom().unwrap().as_u64_pair().unwrap(), [0x0_u64, 0x7fff800000000000_u64]);
    assert_eq!(A(&mut c.stack, &ubig!(0x00000000000000004fffffffffffffff)).as_atom().unwrap().as_u64_pair().unwrap(), [0x4fffffffffffffff_u64, 0x0_u64]);
}
```

indicates the direct atom pair case is swapped; correcting now.  @joemfb

2023-11-17 17:11 UTC, eamsden commented
@sigilante I would like @joemfb's review on this before merging. I'm not presently in a state where I can be confident in my own judgement of the code or the tests.

2023-11-17 20:06 UTC, joemfb approved these changes
this will do

2023-11-17 21:58 UTC, merged