2stackz: gc top frame by flipping polarity
urbit/ares pull request #175
Opened 2023-12-11 03:34 UTC by eamsden

This prevents garbage from accumulating in the top frame, while also permitting us to preserve stuff between events there.

Once the PMA is merged this will allow us to retain the warm and hot states on the stack.

2023-12-11 18:28 UTC, drbeefsupreme requested changes

2023-12-11 19:19 UTC, ashelkovnykov requested changes

2023-12-11 19:19 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +            *new_frame_pointer.add(ALLOC) = self.start as u64;
Should be `self.start.add(self.size)`

2023-12-11 19:19 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +            self.pc = false;
Can be moved out of `if` statement

2023-12-11 19:19 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +            self.pc = false;
Same as above

2023-12-11 19:31 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +            *frame_pointer.sub(ALLOC + 1) = start as u64; // "alloc pointer" from "previous" frame
This is a good concern. I think it should be okay, because `prev_stack_pointer` is the first value that should become `null`. If I recall correctly, I recommended changing the value from `self.start` to `null` to more easily identify errors via a `NULL_PTR` exception, and not out of necessity for correctness of the algorithm.

2023-12-11 20:46 UTC, eamsden commented on rust/ares/src/jets/hot.rs
> +        let mut it = self;
not quite correct: the type of `self` is `&mut Hot`, not `Hot`. We are cloning the reference not the object, which is why this works. When we assign to `it.0` we overwrite the pointer in the original object.

Note also (below) that when we reassign `it` we take a mutable reference to the `next` field in the dereferenced struct.

2023-12-11 20:46 UTC, eamsden commented on rust/ares/src/mem.rs
> +            *new_frame_pointer.add(ALLOC) = self.start as u64;
Good catch

2023-12-11 20:47 UTC, eamsden commented on rust/ares/src/mem.rs
> +            *new_frame_pointer.add(ALLOC) = self.start as u64;
fixed in 002aba5

2023-12-11 20:52 UTC, eamsden commented on rust/ares/src/mem.rs
> +            *frame_pointer.sub(ALLOC + 1) = start as u64; // "alloc pointer" from "previous" frame
Yes `prev_stack_pointer` being null will break the loop in `senior_pointer_first`

2023-12-11 21:10 UTC, eamsden commented on rust/ares/src/jets/hot.rs
> +        let mut it = self;
@drbeefsupreme `self` has type `&mut Hot` so I can write through the reference, but is itself immutable (i.e. I can't assign a new mutable reference to that name). So I copy the *reference* into a mutable variable so I can change which reference I will write through as I traverse the Hot state.

2023-12-11 21:10 UTC, eamsden commented on rust/ares/src/jets/hot.rs
> +        let mut it = self;
(One thing to note here is that the hot state is turning into a HAMT in the codegen PR, so this implementation is temporary.)

2023-12-11 21:15 UTC, drbeefsupreme commented on rust/ares/src/jets/hot.rs
> +        let mut it = self;
Neat, thanks!

2023-12-11 21:17 UTC, drbeefsupreme commented on rust/ares/src/mem.rs
> +            *frame_pointer.sub(ALLOC + 1) = start as u64; // "alloc pointer" from "previous" frame
Sounds good

2023-12-11 21:21 UTC, drbeefsupreme approved these changes

2023-12-12 13:58 UTC, ashelkovnykov approved these changes

2023-12-12 13:58 UTC, merged