`ares_crypto`
urbit/ares pull request #189
Opened 2023-12-17 23:58 UTC by matthew-levan

2023-12-18 16:48 UTC, eamsden requested changes

2023-12-18 16:48 UTC, eamsden commented on rust/ares_crypto/src/ed25519.rs
> -    // tests comparing urcrypt and ares_crypto output for ed25519 functions go here
please leave this comment in and extend it with the cargo command to run these tests, since a regular `cargo test` will not run them

2023-12-22 01:12 UTC, eamsden requested changes
Actually looks pretty good, but I tagged a couple of issues.

2023-12-22 01:12 UTC, eamsden commented on rust/ares/src/noun.rs
> +    }
No.

- `transmute` is banned
- This will return a mutable reference to the existing direct atom, causing the atom to be modified by any writes through the mutable reference.

If this is being used to construct a direct atom by creating a local initialized to `D(0)` and mutating it, then there are a couple of alternatives:

1. Create a mutable local of type `[u8; 8]` and, when it is properly initialized, call `u64::from_le_bytes()` and initialize the atom from there
2. Create an indirect atom using `IndirectAtom::new_raw_mut_bytes()` and call `normalize_to_atom()` afterwards.

The second approach is always preferred because it ensures we do not accidentally construct a floating indirect atom or cell by overflowing the 63 bits of a direct atom.

2023-12-22 01:16 UTC, eamsden requested changes
Using `as_mut_bytes()` on atoms will cause these atoms to be mutated in place, breaking referential transparency. Please correct all instances of this.

2023-12-22 01:16 UTC, eamsden commented on rust/ares/src/noun.rs
> +
No. See above.

2024-01-08 22:10 UTC, matthew-levan commented
> Using `as_mut_bytes()` on atoms will cause these atoms to be mutated in place, breaking referential transparency. Please correct all instances of this.

Done. Now working on ensuring zero-length messages are handled correctly.

2024-01-08 23:15 UTC, matthew-levan commented
@eamsden I ripped out the `as_mut_bytes` implementation from `DirectAtom` and replaced instances where it was used with new `IndirectAtom` allocations which I copy data into. I've also updated jets to handle zero-lengths correctly and added tests to demonstrate. This is ready for another review. The code isn't the cleanest, but I'm tagging you here for expediency nonetheless.

2024-01-17 22:36 UTC, eamsden requested changes
No `as_mut_ptr()` for atoms!

2024-01-17 22:36 UTC, eamsden commented on rust/ares/src/jets/lock/aes.rs
> +                ac_siv_data.as_mut_ptr() as *mut &mut [u8],
why is this doubly indirected?

2024-01-17 22:36 UTC, eamsden commented on rust/ares/src/noun.rs
> +
this should not exist. If a noun has already been created then we should never mutate it. If we need to write into a mutable buffer to make a noun then allocate a new one with `IndirectAtom::new_raw_mut_bytes`

2024-01-18 02:31 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +                ac_siv_data.as_mut_ptr() as *mut &mut [u8],
Good question, I'm not sure exactly what's going on here or why it works. How are the lengths of the byte buffers in `AcAesSivData` structs being translated to the lengths of the byte slices in `siv_data` here? By constructing the `siv_data` variable as we do here, are we getting a slice of byte slices whose elements are `[bytes, length]`? If that's the caes, I'm not sure that's desirable. The tests (taken from both IETF test cases and `dojo` examples) do pass, though.

2024-01-18 02:34 UTC, matthew-levan commented
`_allocate_ads` means "allocate associated datas", not "allocate atoms". I
clarify this to note that we aren't using `ac_siv_data.as_mut_ptr()` to get
a mutable pointer to an atom. Does that make sense?

On Wed, Jan 17, 2024 at 5:36 PM Edward Amsden ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> No as_mut_ptr() for atoms!
> ------------------------------
>
> In rust/ares/src/jets/lock/aes.rs
> <https://github.com/urbit/ares/pull/189#discussion_r1456571133>:
>
> >      ) -> Result {
>          unsafe {
> -            let siv_data = _allocate_atoms(stack, ads)?;
> +            let ac_siv_data = _allocate_ads(stack, ads)?;
> +            let siv_data: &mut [&mut [u8]] = std::slice::from_raw_parts_mut(
> +                ac_siv_data.as_mut_ptr() as *mut &mut [u8],
>
> why is this doubly indirected?
> ------------------------------
>
> In rust/ares/src/noun.rs
> <https://github.com/urbit/ares/pull/189#discussion_r1456573596>:
>
> > +    pub fn as_mut_bytes(&mut self) -> &mut [u8] {
> +        unsafe { from_raw_parts_mut(self.data_pointer_mut() as *mut u8, self.size() << 3) }
> +    }
> +
>
> this should not exist. If a noun has already been created then we should
> never mutate it. If we need to write into a mutable buffer to make a noun
> then allocate a new one with IndirectAtom::new_raw_mut_bytes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/ares/pull/189#pullrequestreview-1828329346>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRH4OWUYQRJ5FKW2DDDYPBG5ZAVCNFSM6AAAAABAYWSHKKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMRYGMZDSMZUGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-01-18 04:02 UTC, eamsden commented
> `_allocate_ads` means "allocate associated datas", not "allocate atoms". I clarify this to note that we aren't using `ac_siv_data.as_mut_ptr()` to get a mutable pointer to an atom. Does that make sense?


that makes sense, but the PR still adds an `as_mut_ptr()` method for indirect atoms which simply should not exist.

2024-01-18 13:41 UTC, matthew-levan commented
Hm maybe it did at one time but I've since removed it. The only
modification to `noun.rs` now is the addition of `IndirectAtom::
new_raw_mut_bytearray`.

On Wed, Jan 17, 2024 at 11:02 PM Edward Amsden ***@***.***>
wrote:

> _allocate_ads means "allocate associated datas", not "allocate atoms". I
> clarify this to note that we aren't using ac_siv_data.as_mut_ptr() to get
> a mutable pointer to an atom. Does that make sense?
>
> that makes sense, but the PR still adds an as_mut_ptr() method for
> indirect atoms which simply should not exist.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/urbit/ares/pull/189#issuecomment-1897754578>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV2DQRHN3PVQTIPKTW6NYELYPCNFTAVCNFSM6AAAAABAYWSHKKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQOJXG42TINJXHA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-02-01 09:57 UTC, ashelkovnykov requested changes

2024-02-01 09:57 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/sha.rs
> +
Do these tests have any significance? Or are they based on dojo calls from a ship running on Vere?

Theoretically, the NIST is supposed to have standardized test cases, but both of the links I've found are returning a 503...
[1](https://csrc.nist.gov/groups/ST/toolkit/examples.html)
[2](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Standards-and-Guidelines/documents/examples/SHA256.pdf)

2024-02-01 09:57 UTC, ashelkovnykov commented on rust/ares_crypto/src/ed25519.rs
> +        // assert_eq!(signature, test_signature);
Cruft left over from getting `ares_crypto` to work?

2024-02-01 09:57 UTC, ashelkovnykov commented on rust/ares_crypto/src/ed25519.rs
> +    // }
Cruft left over from getting `ares_crypto` to work?

2024-02-01 09:57 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/ed.rs
> +
Is there any significance to these tests, or are they just from the dojo of a ship running on Vere?

2024-02-01 09:57 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/ed.rs
> +        secret[0..pub_bytes.len()].copy_from_slice(sec_bytes);
copy-paste error

2024-02-01 14:00 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +
It's just one I got from the `dojo`.

2024-02-01 14:00 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +
Same answer as above.

2024-02-01 14:04 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +        secret[0..pub_bytes.len()].copy_from_slice(sec_bytes);
Not sure what you mean here. Will you clarify please?

2024-02-01 14:05 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +
The significance is that they are tests from a real Vere `dojo`, yes. Future work to add test vectors from RFC 8032 is noted in the above comment.

2024-02-01 14:07 UTC, matthew-levan commented on rust/ares_crypto/src/sha.rs
> +    let mut result = hasher.finalize();
Nice, good catch.

2024-02-01 14:14 UTC, matthew-levan commented on rust/ares/src/noun.rs
> +        let word_size = (std::mem::size_of::<[u8; N]>() + 7) << 3;
I think you're right, though-- take, for example, `N` is `8`. In the case of a left shift (as written), the result is `64`, not `1` as it should be.

2024-02-01 14:23 UTC, matthew-levan commented on rust/ares/src/jets/lock/ed.rs
> +        secret[0..pub_bytes.len()].copy_from_slice(sec_bytes);
Ah, nevermind!

2024-02-02 05:08 UTC, ashelkovnykov commented on rust/ares_crypto/src/ed25519.rs
> +    // }
Ah, nevermind - I see now. It's just a stub for a test that's yet unimplemented (unlike the other functions in this file, `shar` is currently only tested in relation to `urcrypt`).

2024-02-02 05:14 UTC, ashelkovnykov commented
This PR is almost ready to ship.

Minimum necessary changes:
- [byte array allocation size bug](https://github.com/urbit/ares/pull/189#discussion_r1472702826)
- [SHA message slicing bug](https://github.com/urbit/ares/pull/189#discussion_r1474046046)

Changes I'd prefer to have, but aren't necessary to merge:
- [singleton `hasher`s](https://github.com/urbit/ares/pull/189#discussion_r1472719317)
- Implement test cases from well known sources (e.g. RFCs, NIST, etc.). We can get away without these, methinks, since we're now relying on Rust crates which are very well tested - but better safe than sorry!

2024-02-02 15:47 UTC, matthew-levan reviewed
Thanks for the review @ashelkovnykov. I pushed a couple commits to address the byte array allocation size bug and the SHA message slicing bug. With respect to the single `hasher` use in our SHA module, where would the singleton be initialized? A global? Passed in to the functions via the caller? I propose merging ASAP and circling back to use the singleton pattern afterwards.

2024-02-02 20:18 UTC, matthew-levan commented on rust/ares/src/jets/lock/aes.rs
> +                ac_siv_data.as_mut_ptr() as *mut &mut [u8],
@ashelkovnykov would you mind taking a look at this as well?

2024-02-02 20:20 UTC, matthew-levan commented on rust/ares/src/jets/lock/sha.rs
> +            message.copy_from_slice(&ruz.as_bytes()[0..msg_len]);
We definitely can @ashelkovnykov, a pretty easy job too.

2024-02-07 14:24 UTC, ashelkovnykov commented on rust/ares/src/jets/lock/aes.rs
> +                ac_siv_data.as_mut_ptr() as *mut &mut [u8],
This is correct:

The input is a list of atoms which are converted into a contiguous array of `AcAesSivData` objects, which is then used by the encoder. We pass it from the jets code as an array of byte arrays, because we need to reverse the byte ordering prior to encoding for each element. When used by the encoder, it implicitly converts our input to just a byte buffer. Vere does something similar.

We could make the byte ordering reversal explicit in the jet code and then pass just a byte buffer, if we think that's best. However, that's a different discussion than correctness.

2024-02-07 14:47 UTC, ashelkovnykov approved these changes

2024-02-07 21:20 UTC, matthew-levan commented
I removed `nix` from the CI in the latest commit, so it will need to be reverted and the CI error will need to be resolved. I wasn't able to fix the CI error quickly without removing `nix`.

2024-02-08 00:30 UTC, ashelkovnykov commented
@matthew-levan That's okay, @eamsden and I are going to look at fixing the Nix build using `musl`

2024-02-08 00:49 UTC, merged