jets: fix jet_rev
urbit/ares pull request #193
Opened 2023-12-19 18:02 UTC by drbeefsupreme

`jet_rev` had an issue with the indirect atom case. `IndirectAtom::new_raw` would normally be fine since we normalize, but since we're reversing endianness, we end up using the extra space. So the fix is to use `IndirectAtom::new_raw_bytes` instead.

I've also added a test case that catches this, which fails for the previous version.

2023-12-19 18:32 UTC, eamsden commented
@drbeefsupreme this should actually call `IndirectAtom::new_raw_mut_bitslice()` and call `normalize_as_atom` on the indirect atom afterwards.

2023-12-19 23:40 UTC, eamsden requested changes

2023-12-19 23:40 UTC, eamsden commented on rust/ares/src/jets/bits.rs
>          dest[start..end].copy_from_bitslice(&src[(total_len - end)..(total_len - start)]);
just checked and this isn't correct: +rev reverses *block* order, not bit order.

2023-12-19 23:43 UTC, eamsden commented on rust/ares/src/jets/bits.rs
>          dest[start..end].copy_from_bitslice(&src[(total_len - end)..(total_len - start)]);
ideally we have fastpaths for `boz == 0` (bitslice as above) and `boz >= 3` (byteslice) and correct-but-slow loop code for `boz == 1 || boz == 2`

2023-12-20 00:03 UTC, drbeefsupreme commented on rust/ares/src/jets/bits.rs
>          dest[start..end].copy_from_bitslice(&src[(total_len - end)..(total_len - start)]);
Isn't the reversal of block order being handled by the line above it? Otherwise I don't see how the test case I added could be passing (which I got from running `+rev` in dojo).

```
(rev 3 12 0xfaceb00c15deadbeef123456)
> 0x563412efbeadde150cb0cefa
```

I'm tired so maybe I'm misunderstanding. In any case, the fastpaths suggestion is great.

2023-12-20 05:51 UTC, eamsden approved these changes

2023-12-20 05:51 UTC, eamsden commented on rust/ares/src/jets/bits.rs
>          dest[start..end].copy_from_bitslice(&src[(total_len - end)..(total_len - start)]);
you're right, diff-based review delenda est

2023-12-20 15:05 UTC, ashelkovnykov approved these changes

2023-12-20 17:05 UTC, merged