Implement fastpath for `jet_rev` where `boz = 0` and `boz = 3`
urbit/ares pull request #198
Opened 2024-01-11 21:22 UTC by nisfeb

```
Running benches/boz.rs (target/release/deps/boz-c09d868d611fc8e8)
boz 3                   time:   [20.110 ns 20.178 ns 20.282 ns]
                        change: [-3.3792% -3.1311% -2.8160%] (p = 0.00 < 0.05)
                        Performance has improved.
```

2024-01-13 02:23 UTC, nisfeb commented
Improved these cases with help from @eamsden. Based on our implementation, the tests may be incorrect. This also calls into question the correctness of the initial generic case. Either the tests or the cases need to be fixed. The original generic case has been left in place to help the investigation.

2024-01-31 07:15 UTC, ashelkovnykov requested changes
The tests are fine; the code has errors

2024-01-31 07:15 UTC, ashelkovnykov commented on rust/ares/src/jets/bits.rs
> +    let step = len as usize - util::met(boz, dat);
This should be `met(boz, dat_swp)`, since a correct `swp` can return a smaller noun:
```
> `@ub`(swp 2 0b1111.1000.0000)
0b1000.1111
```

2024-01-31 07:15 UTC, ashelkovnykov commented on rust/ares/src/jets/bits.rs
> +            },
This always returns at the granularity of one or more words of memory, which is not in accord with `++swp` in Arvo. For `0x87.6543`, this will return `0xc2a6e10000000000` (exactly 64-bits) and the code in `jet_rev` never right shifts.

2024-01-31 07:15 UTC, ashelkovnykov commented on rust/ares/src/jets/bits.rs
> +                dest.copy_from_slice(dat.as_bytes());
Slice bit length errors here, between `dest` and `dat`

2024-03-19 19:43 UTC, eamsden commented
I'm going to defer this until it comes up in benchmarking.

2024-03-19 19:43 UTC, closed without merging