split stack docs
urbit/ares pull request #64
Opened 2023-07-24 20:27 UTC by drbeefsupreme

Swaps out `stack.md` for `split-stack.md` and `noun-rep.md`

2023-07-26 22:18 UTC, ashelkovnykov requested changes
Partial review: made it to the "Stack Pointer" section of `split-stack.md` and had some strong issues with the documentation that I think might affect the remainder of it, so I ceased review.

Changes to the other files LGTM, though.

2023-07-26 22:18 UTC, ashelkovnykov commented on docs/split-stack.md
> +current stack pointer. For an east frame, substitute "less" with "greater". The
>  For a west frame, the pointers are always ordered as previous allocation
pointer is less than the current frame pointer is less than or equal to the
current stack pointer.

This is a really confusing sentence. It would probably be clearer as a bullet point list. Ex:

For a west frame:
- `prev_alloc_ptr = (frame_ptr - 3)`
- `stack_ptr >= frame_ptr`
- `*(frame_ptr - 2) = prev_alloc_ptr`
- `*(frame_ptr - 1) = prev_stack_ptr`
- `*(frame_ptr) = prev_frame_ptr`

Note that this also includes information from the "Execution Phase" section as well.

While writing this, it occurred to me: why do we need a slot for the previous allocation pointer, if the contents are always `frame_ptr +/- 2`, depending on the polarity? I recall this came up early during the work, but I don't remember what the reason was.

2023-07-26 22:18 UTC, ashelkovnykov commented on docs/split-stack.md
> +|----sYYYAoooSLLFXXXa----|
I think this diagram does more to confuse than to enlighten. My two big issues with it are:
1. It doesn't distinguish between the FP-relative slots and stack slots
2. It makes it appear as if allocation, stack, and frame pointers take up space in memory, as opposed to pointing to parts of memory

I think we'd be better served by having diagrams of the kind @drbeefsupreme made for describing nouns, and then using these notes to refer to them and explain the *why* of the design, not the what.

2023-07-27 14:30 UTC, drbeefsupreme commented on docs/split-stack.md
> +|----sYYYAoooSLLFXXXa----|
1. It does - that's what `X` and `L` are. But I still agree that the diagram is hard to read.
2. This is a good point

I have this in an .svg diagram already, but I'm still tweaking it since I want to use the same one to describe an example of lightweight stack usage and I keep running into issues that make it hard to read. I'll give it another go sometime this week or early next week.

2023-07-27 14:47 UTC, drbeefsupreme commented on docs/split-stack.md
> +current stack pointer. For an east frame, substitute "less" with "greater". The
Agreed that a list of equations is more lucid.

> While writing this, it occurred to me: why do we need a slot for the previous allocation pointer, if the contents are always frame_ptr +/- 2, depending on the polarity? I recall this came up early during the work, but I don't remember what the reason was.

That's only true if there are no additional FP-slots beyond the reserved slots. Right now, it's actually

- prev_alloc_ptr = (frame_ptr - 3 - slots)

You could do this though - you could either put the saved pointers west of `frame_pointer` and additional slots east of `frame_pointer, or put the frame pointer at the westmost word of a west frame, and FP-relative slots to the east. You'd need to save the initial value of `stack_pointer` to tell when it is empty. So you no longer need to include the previous allocation pointer as you point out, but now need to include the initial value of `stack_pointer` for that frame to tell when the lightweight stack is empty.

So you use the same amount of memory, but you end up with a different interface for the programmer. I think the way it currently works ultimately has a better interface. One reason for this is as follows.

When a frame is in "cleanup phase", you have to save the parent frame's pointers in the free space adjacent to the current frame's `alloc_pointer`. Then when you start copying from the current frame's allocations to the previous frame's, you adjust the value of  `prev_alloc_pointer` as you go. So `prev_alloc_pointer` can no longer be calculated relative to the current frame's `frame_pointer`. Thus there's logical continuity going from

```(prev_alloc_pointer, prev_frame_pointer, prev_stack_pointer)` -> `(prev_alloc_pointer, prev_frame_pointer, prev_stack_pointer)```
when you go from execution to cleanup phase, vs

```(prev_frame_pointer, prev_stack_pointer, initial_stack_pointer)` -> `(prev_alloc_pointer, prev_frame_pointer, prev_stack_pointer)```
which is what you get when you have the initial value of `stack_pointer` as a saved pointer instead of `prev_alloc_pointer`.

I thought I had a second reason but I forgot by the time I got here. Just the one reason should be enough though.

2023-07-27 15:49 UTC, ashelkovnykov commented on docs/split-stack.md
> +current stack pointer. For an east frame, substitute "less" with "greater". The
That makes sense - I was misunderstanding how slots were tracked. Thank you for the explanation.

2023-07-27 15:51 UTC, ashelkovnykov commented
@drbeefsupreme Thanks for your response. I'll continue reviewing from where I left off after I review #60 - I think It'll be easier to gauge the documentation after I understand the exact behaviour of the code.

2023-07-28 13:18 UTC, drbeefsupreme commented
I'll add in some edited version of my response to make things more clear.

2023-07-29 01:22 UTC, ashelkovnykov commented on docs/split-stack.md
> +will always have an east polarity, and vice versa.
Since the frame pointer never moves and the allocation pointer always moves towards it, I think it would be better to explain polarity with reference to the frame and allocation pointers instead of the stack and allocation pointers.

2023-08-12 03:40 UTC, eamsden commented on docs/split-stack.md
> +will always have an east polarity, and vice versa.
This is a good point. @drbeefsupreme can you make this change when you get a chance please? Since we merged the split stack I'd like to get the docs updated ASAP

2023-09-01 21:11 UTC, drbeefsupreme commented on docs/split-stack.md
> +will always have an east polarity, and vice versa.
https://github.com/urbit/ares/pull/64/commits/0e3245bfd70f2940d33b9339408ca845cd241532

2023-09-01 21:12 UTC, drbeefsupreme commented on docs/split-stack.md
> +|----sYYYAoooSLLFXXXa----|
Here's an svg: https://github.com/urbit/ares/pull/64/commits/bdf48555292b9a39ca6c9c9f85dd29c91fa491b9

2023-09-01 21:12 UTC, drbeefsupreme commented
Some new revisions, including a much-needed diagram. Can you take another look @ashelkovnykov?

2023-09-07 22:23 UTC, ashelkovnykov requested changes

2023-09-07 22:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +stack pointer (inclusive).
If my above comment is applied, the concepts of "stack side" and "heap side" have already been explained. I also feel that this part is a little unclear, in that the slots and frame pointers are lumped in with the stack. If this section is kept at all, it might be clearer to have something like the following:
```
The stack for a west frame is the memory eastward of the frame pointer
(inclusive) and westward of the current stack pointer (exclusive). The heap 
or a west frame is the memory eastward of the current allocation pointer
(inclusive) and westward of the previous stack pointer (exclusive).

Similarly, the stack for an east frame is the memory westward of the frame
pointer (exclusive) and eastward of the current stack pointer (inclusive).
The heap for an east frame is the memory westward of the current allocation 
pointer (exclusive) and eastward of the previous stack pointer (inclusive). 

The slots and registers for a frame are always stored in the memory between
the previous allocation pointer and the frame pointer (inclusive).
```

2023-09-07 22:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +that stack frame.
Above, the three reserved slots are referred to as "registers"

2023-09-07 22:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +you need to understand what all the pointers are for and what the cleanup phase
"... you need to **first** understand ... "

2023-09-07 22:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +allocation pointer, the polarity is east. Thus, by the process outlined about,
"... the process outlined **above** ..."

2023-09-07 22:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +o free memory
See above: the SVG is so much better that this ASCII diagram should be axed and the reader directed to the visual reference

2023-09-08 01:03 UTC, eamsden commented on docs/split-stack.md
> +o free memory
Agreed. If the SVG is committed it could even be included as a markdown image reference:

```markdown
![alt text](relative_url.svg)
```

2023-09-08 01:04 UTC, eamsden commented on docs/split-stack.md
> +Thus, the current stack frame may be said to have "west" or "east" polarity.
:+1:

2023-09-08 01:06 UTC, eamsden commented on docs/split-stack.md
> +stack pointer (inclusive).
there's no registers in the stack. There are "registers" (fields of the NockStack struct) which define the current state of the stack, but words referenced by a fixed offset from the frame pointer are called "slots"

2023-09-08 01:07 UTC, eamsden commented on docs/split-stack.md
> +that stack frame.
The only thing which is correct to call a "register" in this document is the *current* stack/frame/allocation pointers.

2023-09-08 01:11 UTC, ashelkovnykov commented on docs/split-stack.md
> + - `prev_alloc_ptr = frame_ptr - 3 - n`
Scratch that - forgot that we're talking about the pointer, not the value *at* the pointer

2023-09-08 01:13 UTC, ashelkovnykov commented on docs/split-stack.md
> +stack pointer (inclusive).
Updated comment to remove calling the three permanent slots "registers"

2023-09-08 01:14 UTC, ashelkovnykov commented on docs/split-stack.md
> +o free memory
Or an `img` tag so that we can control the width/height of the image, plus link to the original

2023-09-08 04:23 UTC, ashelkovnykov requested changes
Forgot suggestions exist in my previous review. Used suggestions in places where I'm more certain of changes being required / preferable.

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +recursively chased and copied to the parent frame's allocation arena. This is
See above.
```
Pointers to result components which fall within the current frame are tracked down recursively from the root and copied to the parent frame's stack.
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +only ever point to other memory within in the same stack frame, or more senior
```suggestion
only ever point to other memory within the same stack frame, or more senior
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +arena, and pushing both constituent noun pointers onto the lightweight stack with the
```suggestion
Copying a cell results in a new cell allocation to the parent frame's
stack, and pushing both constituent noun pointers onto the lightweight stack with the
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +in each stack frame for the parent frame's pointers.
```suggestion
and in fact is then equal to `prev_alloc_ptr`. This means that only two slots need to be reserved
in each stack frame for the parent frame's pointers.
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +have been a better choice.
```suggestion
Now we can no longer test whether the lightweight stack is empty by computing `stack_ptr == frame_ptr`. Instead, we need to save the
initial location of `stack_ptr` in a reserved slot. This is because it is not a
fixed offset from `frame_ptr` since the total number of slots in a given stack frame
can vary. Therefore, we have the same number of reserved slots in the execution phase.
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +varying as in the execution phase), the emptiness of the lightweight stack can
```suggestion
In the cleanup phase, since the number of slots is fixed at 3 (as opposed to
the varying number in the execution phase), the emptiness of the lightweight stack can
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +depends on how you order them). So we no longer need to save the initial value
```suggestion
be determined by checking if it's equal to one of the reserved slots.
Therefore we no longer need to save the initial value
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +of `stack_ptr` in the cleanup phase.
```suggestion
of `stack_ptr` in the cleanup phase. However, the frame pointer is now `alloc_ptr`-relative,
therefore we need to save the location of `prev_alloc_ptr` (since this was implicitly identical to `frame_ptr`).
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> +Thus we would have two different sets of reserved pointers in the execution and
```suggestion
Thus, we have two different sets of reserved pointers between the execution and
```

2023-09-08 04:23 UTC, ashelkovnykov commented on docs/split-stack.md
> + stack is empty in both the execution and cleanup phases.
```
This adds complexity for the programmer with no space or performance benefit to the system.
```

2023-09-08 15:21 UTC, eamsden commented on docs/split-stack.md
> +Every time an allocation is made or reclaimed, the allocation
It's because objects live in the "heap"/allocation area. The lightweight stack and stack slots only hold fixed-size references or datums. The allocation area is for arbitrary-sized nouns (and bytecode...and HAMTs...and...)

2023-09-13 17:02 UTC, drbeefsupreme commented
I need to put a temporary pause on this, since my work on jet cold state has made it apparent that `Hamt::preserve` probably shouldn't use the lightweight stack. Once that's settled I'll come back to this.

2023-11-24 21:03 UTC, eamsden commented
This is pretty stale, we'll revisit docs for this later.

2023-11-24 21:03 UTC, closed without merging