jets: fix cut for 0 run
urbit/ares pull request #70
Opened 2023-08-26 14:46 UTC by eamsden

Fixes #69

2023-08-28 17:35 UTC, drbeefsupreme commented
Yup, this works!

2023-08-28 19:44 UTC, philipcmonk requested changes
Thanks for fixing this!

2023-08-28 19:44 UTC, philipcmonk commented on rust/ares/src/jets/math.rs
> +        }
Typically we use the `D` shortcut for this.

```suggestion
        return Ok(D(0));
```

2023-08-29 03:26 UTC, philipcmonk approved these changes

2023-08-29 12:48 UTC, merged

2023-08-29 23:17 UTC, ashelkovnykov reviewed
LGTM