hamt: preserve traversal_stack uses rust stack
urbit/ares pull request #84
Opened 2023-09-13 17:48 UTC by drbeefsupreme

This was using the lightweight stack, but this presented the following issue: `NockStack::copy()` can be called during the `Hamt::preserve()` call, and the lightweight stack may not be empty. `NockStack::copy()` presumes that the lightweight stack is empty when it is called, and thus tried to pop elements that `preserve()` had pushed onto it.

`NockStack::copy()` should probably assert that the lightweight stack is empty when its called.

I'm making the assert `stack_is_empty()` a separate PR since its a separate concern, but I have tested that it works fine with this PR and several jamfiles where `copy()` is called many times.

2023-09-13 17:59 UTC, drbeefsupreme commented
Hold off on this one moment... I thought I tested this with my jet cold state branch, but I must have made a mistake somewhere since now its not working.

2023-09-13 18:01 UTC, drbeefsupreme commented
Nevermind, all good. I just forgot that I had some of the changes in the jet cold state branch I needed stashed, not committed, and its working with the stash restored.

2023-09-14 00:41 UTC, ashelkovnykov commented
Haven't looked at the code in this PR yet, but I just found that `%memo` hints were causing Ares crashes on `preserve` calls to the cache in my stack trace test pill. As another data point, I'm going to try applying this PR to my branch to see if it fixes the crashes.

2023-09-14 02:28 UTC, eamsden requested changes
Just one change for idiomatic/succinct Rust.

2023-09-14 02:28 UTC, eamsden commented on rust/ares/src/hamt.rs
> +                };
```suggestion
                let (stem, mut position) = traversal_stack[traversal_depth - 1].expect("Attempted to access uninitialized array element");
```

`.expect()` is the canonical way to do this for both `Result` and `Option`

2023-09-14 04:34 UTC, ashelkovnykov commented
> Haven't looked at the code in this PR yet, but I just found that `%memo` hints were causing Ares crashes on `preserve` calls to the cache in my stack trace test pill. As another data point, I'm going to try applying this PR to my branch to see if it fixes the crashes.

Confirmed that this PR fixes `%memo` hints in my stack traces pill

2023-09-14 17:56 UTC, eamsden approved these changes

2023-09-14 17:56 UTC, merged

2023-09-14 20:18 UTC, ashelkovnykov reviewed
Late, but LGTM.

The code all looks logically correct, though I don't understand the Ares `Hamt` code fully (for lack of trying).