jets: non-sham dashboard
urbit/ares pull request #92
Opened 2023-09-22 22:33 UTC by eamsden

2023-09-23 04:30 UTC, eamsden commented
### Booting the baby pill
![image](https://github.com/urbit/ares/assets/54573/469d43b5-92ce-4cd7-9eb4-f8fd1e09707c)

2023-09-28 04:01 UTC, eamsden commented
@ashelkovnykov @philipcmonk this is ready for review now

2023-10-16 21:52 UTC, ashelkovnykov requested changes
Partial pair review w/ @eamsden

2023-10-16 23:48 UTC, ashelkovnykov requested changes

2023-10-16 23:48 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +    pub unsafe fn struct_is_in<T>(&self, ptr: *const T, count: usize) {
`assert_struct_is_in` would be a more accurate name

2023-10-16 23:48 UTC, ashelkovnykov commented on rust/ares/src/mem.rs
> +    unsafe fn noun_in(&self, noun: Noun) {
TODO: Compare this to the version from the debug investigation

2023-10-17 00:04 UTC, ashelkovnykov commented on rust/ares/src/interpreter.rs
> +                            Some(dint.hint),
Need to overwrite `dint.hint` with `res` (which is actually the `clue`) in `11D::ComputeResult`

2023-10-17 00:07 UTC, ashelkovnykov commented on rust/ares/src/jets/hot.rs
> +const HOT_STATE: &[(&[Either<u64, (u64, u64)>], u64, Jet)] = &[
This needs to match the sham jet dashboard at the time of merge

2023-10-18 02:04 UTC, eamsden reviewed
I approve of these changes but since I originally opened the PR I cannot officially approve them.

2023-10-18 03:23 UTC, ashelkovnykov approved these changes

2023-10-18 03:24 UTC, merged