implement as_bytes() on Atom
urbit/ares pull request #96
Opened 2023-09-29 02:23 UTC by philipquirk

This implements as_bytes() on Atom so you can handle direct and indirect atoms the same. For both it returns a reference to the underlying data as &[u8].

2023-09-29 02:34 UTC, eamsden requested changes

2023-09-29 02:34 UTC, eamsden commented on rust/ares/src/noun.rs
> +
```suggestion
```
as above

2023-09-29 02:34 UTC, eamsden commented on rust/ares/src/noun.rs
> +    }
```suggestion
```
as above

2023-09-29 02:34 UTC, eamsden commented on rust/ares/src/noun.rs
> +    }
```suggestion
```
Nouns are immutable, please don't provide mutable accessors to them.

2023-09-29 23:16 UTC, eamsden approved these changes

2023-09-29 23:17 UTC, eamsden commented
@philipquirk please run cargo fmt.

2023-10-04 00:41 UTC, philipquirk commented
> @philipquirk please run cargo fmt.

Sorry I missed this message. I didn't even know about 'cargo fmt' but it's nice. And I see you ran it for me.

2023-10-04 00:48 UTC, eamsden approved these changes

2023-10-04 00:48 UTC, merged